# _config.production.yml

url: "https://serverboi.org"
baseurl: ""  # empty string because you're deploying to the root domain

# Optional: mark production explicitly
environment: production

compress_html:
  ignore:
    envs: []  # override to not ignore any envs — so minification works in prod
